name: bmi_calculator
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-382.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.14
  flutter_gen_runner: ^5.1.0+1
  syncfusion_flutter_gauges: ^20.3.57
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  isar_generator: ^3.0.5


flutter:
  uses-material-design: true
  assets: 
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600



flutter_native_splash:
  color: "#597CF1"
  image: assets/images/splash_screen_image.png
  android_12: 
    color: "#597CF1"
    image: assets/images/splash_screen_image.png